fcrepo-exts/migration-utils

src/main/java/org/fcrepo/migration/handlers/BasicObjectVersionHandler.java
src/test/resources/exported/example3-foxml.xml

Resolves https://jira.duraspace.org/browse/FCREPO-1585

Relaxed referential integrity rules for RELS-INT.

---

pom.xml

Resolves: https://jira.duraspace.org/browse/FCREPO-3045
Note, the 'repositories' update in the pom.xml should be reverted when the ocfl-java artifacts are published to Sonatype
Adds ocfl-java dependencies
Build the application, dependencies should be downloaded.
@fcrepo4-exts/migration-utils-committers

Add ocfl-java dependencies

---

pom.xml

**Migration utils: Upgrade commons-codec version to match UWM OCFL lib**
* * *
https://jira.duraspace.org/browse/FCREPO-3055
Updates commons-codec version from 1.6 to 1.13 to meet dependencies from ocfl-java 
Due to https://github.com/UW-Madison-Library/ocfl-java/commit/bdcf59e9694f94f3bf3e873c0a0e0cbb526a3187 seemingly breaking migration-utils build
* pom.xml version change for commons-codec from 1.6 to 1.13 
Ensure commons-codec functionality in https://github.com/fcrepo4-exts/migration-utils/blob/master/src/main/java/org/fcrepo/migration/foxml/FoxmlInputStreamFedoraObjectProcessor.java#L356 is unaffected by the upgrade. 

Fcrepo 3055

---

.travis.yml
src/main/java/org/fcrepo/migration/f4clients/OCFLFedora4Client.java
src/test/java/org/fcrepo/migration/f4clients/OCFLFedora4ClientTest.java
src/test/resources/staging/.gitignore

**Removed testing with JDK8 from Travis**
* * *
**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-3068
* Removed jdk8 from Travis configuration file. JDK8 is no longer supported by the project.
* Added missing testing resource: test/resources/staging
* Cosmetic changes
Travis should no longer report broken builds for Java 8
@Surfrdan @pwinckles

Removed testing with JDK8 from Travis

---

src/main/java/org/fcrepo/migration/f4clients/OCFLFedora4Client.java
src/test/java/org/fcrepo/migration/f4clients/OCFLFedora4ClientIT.java
src/test/resources/spring/ocfl-it-setup.xml

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-3071
Added the createResource method in the OCFLFedora4Client class
and a simple test. Also changed storage location in the fedora4Client
bean. The staging and storage paths in the bean fedora4Client might need to be changed.
This includes a test, but the tests will probably fail as the staging location does not exist.
Changes in https://github.com/fcrepo4-exts/migration-utils/pull/62 should resolve the issue.

Added the createResource method

---

src/main/java/org/fcrepo/migration/f4clients/OCFLFedora4Client.java
src/test/java/org/fcrepo/migration/f4clients/OCFLFedora4ClientIT.java

This task is to implement the 'createVersionSnapshot()' method of the OCFL client:
https://github.com/fcrepo4-exts/migration-utils/blob/master/src/main/java/org/fcrepo/migration/f4clients/OCFLFedora4Client.java
Also provides additional checks in existing integration test in testExists()
https://github.com/fcrepo4-exts/migration-utils/blob/master/src/main/java/org/fcrepo/migration/f4clients/OCFLFedora4ClientIT.java
* * *
**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-3072
* Other Relevant Links (Mailing list discussion, related pull requests, etc.)
Not relevant
Implements the 'createVersionSnapshot()' method
A in-depth description of the changes made by this PR. Technical details and possible side effects.
Example:
*  Copy the staged object into the storage root
*  Sets …

Fcrepo 3072

---

README.md
pom.xml
src/main/java/org/fcrepo/migration/Migrator.java
src/main/java/org/fcrepo/migration/pidlist/PidListManager.java
src/main/java/org/fcrepo/migration/pidlist/ResumePidListManager.java
src/main/java/org/fcrepo/migration/pidlist/UserProvidedPidListManager.java
src/test/java/org/fcrepo/migration/pidlist/ResumePidListManagerIT.java
src/test/java/org/fcrepo/migration/pidlist/ResumePidListManagerTest.java
src/test/java/org/fcrepo/migration/pidlist/UserProvidedPidListManagerIT.java
src/test/java/org/fcrepo/migration/pidlist/UserProvidedPidListManagerTest.java
src/test/resources/spring/ocfl-pid-it-setup.xml
src/test/resources/spring/ocfl-user-it-setup.xml

1. ResumePidList
- Allows resuming the migration from the point of the last successfully migration F3 object
2. UserProvidedPidList
- Allows for user to provide a list of PIDs to migrate
Resolves:
https://jira.duraspace.org/browse/FCREPO-3111 , and
https://jira.duraspace.org/browse/FCREPO-3112
Two new "PidListManagers" have been created. They can be configured in the spring.xml as follows:
```
<bean id="migrator" class="org.fcrepo.migration.Migrator">
<property name="source" ref="${migration.layout:exported}" />
<property name="handler" ref="objectAbstraction" />
<property name="limit" value="${migration.limit:2}" />
<property name="pidListManagers">
<list>
<bean class="org.fcrepo.migration.pidlist.UserProvidedPidListManager">
<constructor-arg name="pidListFile" …
```

Allow selection of PIDs/Objects to migrate with to new selectors

---

README.md
conf/fedora3.xml
src/main/java/org/fcrepo/migration/f4clients/OCFLFedora4Client.java
src/test/java/org/fcrepo/migration/f4clients/OCFLFedora4ClientIT.java

Resolves: https://jira.duraspace.org/browse/FCREPO-3110
This PR adds support for PAIRTREE and TRUNCATED storage layouts
After building the project, run a local migration three times, using each of the three options:
```
java -Dmigration.ocfl.layout=FLAT
```
```
java -Dmigration.ocfl.layout=PAIRTREE
```
```
java -Dmigration.ocfl.layout=TRUNCATED
```
If no option is provided, the default layout should be `FLAT`
@fcrepo4/committers and @pwinckles

Add support for PAIRTREE and TRUNCATED storage layouts

---

src/main/java/org/fcrepo/migration/f4clients/OCFLFedora4Client.java

Resolves: https://jira.lyrasis.org/browse/FCREPO-3133
The `staging` directory is already removed when the tool terminates. The only difference this update makes is to `move` the staged content during the migration.

MOVE staged content into OCFL

---

src/main/java/org/fcrepo/migration/PicocliMigrator.java

- Changed "working-dir" option to "target-dir"
- Added "Choices" information to the help output for --layout
- `--limit` now indicates meaning of default value
Resolves: https://jira.lyrasis.org/browse/FCREPO-3132

Address usability feedback

---

src/main/java/org/fcrepo/migration/PicocliMigrator.java
src/main/resources/logback.xml

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3144
* Set default `org.fcrepo.migration` package log level to INFO (changed from DEBUG)
* Set `org.fcrepo.migration` package log level to DEBUG when debug flag is set
New method in PicocliMigrator class: `setDebugLogLevel()`, called at beginning of execution
* Run the migration utility without the 'debug' flag:  only INFO and above messages should be shown on STDOUT
* Run the migration utility with the 'debug' flag:  DEBUG messages should be shown for all classes in the `org.fcrepo.migration` package.
This implementation of debug logging is not ideal, as the setDebugLogLevel() method explicitly calls the Logback logging class (`ch.qos.logback.classic.Logger`) to set the log level, thereby bypassing the benefits of using the slf4j …

Enable debug logging only when debug flag set

---

src/main/java/org/fcrepo/migration/handlers/ocfl/HackyOcflDriver.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3147
* Use and log OCFL versionId value of 'ignored', to indicate that legacy versionIds are not migrated to OCFL objects.
* Use content-type of `application/octet-stream` (the least specific mime type) as contentType argument to OCFL client nonRDF resource create/update method, as contentType is not used by the OCFL client.
Run the migration-utils migration to OCFL.  The INFO level log output should show a versionId of 'ignored' for migrated object versions.  There should be no other change to migrated content.
@awoods

Use migrated versionId of 'ignored' for OCFL

---

README.md
src/main/java/org/fcrepo/migration/PicocliMigrator.java
src/main/java/org/fcrepo/migration/foxml/DirectoryScanningIDResolver.java

Resolves: https://jira.lyrasis.org/browse/FCREPO-3149
The tool will create an index at the user-provided location if it does not already exist, and use the index if it does exist.
1. Run the tool without the `-i` option
- Should run as before (creates temp index, deletes index after tool terminates)
1. Run the tool with `-i` option, pointing to non-existent directory
- Index should be created at user-provided location, persisting after run completes
1. Run the tool with `-i` option, pointing to directory created in previous step
- Index should be used at user-provided location, persisting after run completes
- Check that timestamps have not been updated on files in index directory
@sprater

Add option for user-provided indexDir

---

src/main/java/org/fcrepo/migration/f4clients/OCFLFedora4Client.java

Correct the import packages to align with changes in the ocfl-java client code.
Before PR, build fails
```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /sw/var/www/fcrepo4/migration-utils/src/main/java/org/fcrepo/migration/f4clients/OCFLFedora4Client.java:[23,42] cannot find symbol
symbol:   class FileSystemOcflStorage
location: package edu.wisc.library.ocfl.core.storage
[ERROR] /sw/var/www/fcrepo4/migration-utils/src/main/java/org/fcrepo/migration/f4clients/OCFLFedora4Client.java:[94,24] cannot find symbol
symbol:   variable FileSystemOcflStorage
location: class org.fcrepo.migration.f4clients.OCFLFedora4Client
[INFO] 2 errors 
[INFO] …
```

Correct OCFL imports

---

src/main/java/org/fcrepo/migration/foxml/DirectoryScanningIDResolver.java
src/test/java/org/fcrepo/migration/foxml/AkubraFSIDResolverIT.java

Resolves: https://jira.lyrasis.org/browse/FCREPO-3185
Adds a check to ensure that user-provided index-dir is non-empty before assuming it contains index files.
1. New integration test should pass during build
1. Also, create an empty directory
- Run migration utils with arg `-i path/to/empty/dir`
- Tool should create index files within the previously empty dir.

Ensure ID index dir is non-empty before assuming it contains index files

---

README.md
conf/fedora3.xml
pom.xml
src/main/java/org/fcrepo/migration/PicocliMigrator.java
src/main/java/org/fcrepo/migration/handlers/ocfl/ArchiveGroupHandler.java
src/test/java/org/fcrepo/migration/foxml/FoxmlDirectoryDFSIteratorTest.java
src/test/java/org/fcrepo/migration/handlers/ocfl/ArchiveGroupHandlerTest.java
src/test/resources/spring/ocfl-pid-it-setup.xml
src/test/resources/spring/ocfl-user-it-setup.xml

Update mockito dependency
Add additional parameter to 'ArchiveGroupHandler'
- and update spring.xml files accordingly
Add Tika dependency for mimetype to extension mapping
Add ArchiveGroupHandlerTest unit test
Add commandline argument for enabling addition of file extensions
Update README with new commandline argument
Resolves: https://jira.lyrasis.org/browse/FCREPO-3181
The basic idea is that you want to run two migrations, one with the `--extensions` option, and one without... then verify that the migrated datastreams do or do not have file extensions.
1. Verify migrated datastreams have file extensions
```
java -jar target/migration-utils-4.4.1-SNAPSHOT-driver.jar [options] -x
```
2. Verify migrated datastreams do not have file extensions (notice, no `-x` option)
```
java -jar …
```

Add option for migrated datastreams to have file extensions

---

.gitignore
README.md
src/main/java/org/fcrepo/migration/PicocliMigrator.java

This hostname is used to replace the default placeholder in 'E' and 'R' datastream URLs
Unit tests already exist for this functionality:
- https://github.com/fcrepo4-exts/migration-utils/blob/master/src/test/java/org/fcrepo/migration/Example1TestSuite.java#L18
and
- https://github.com/fcrepo4-exts/migration-utils/blob/master/src/test/java/org/fcrepo/migration/Example1TestSuite.java#L202
This update simply exposes the existing functionality as a user option
Resolves: https://jira.lyrasis.org/browse/FCREPO-3198
1. Ensure that new option is shown in usage output
```
java -jar migration-utils.jar --help
```
- Observe new `--f3hostname` option
2. Ensure functionality works
- Find a test F3 object that contains either an `E` or `R` datastream (locally, I use: "1711.dl:CModelUWDCObject")
- Run …

Add user option for specifying F3 hostname

---

src/main/java/org/fcrepo/migration/f4clients/OCFLFedora4Client.java

Resolves: https://jira.lyrasis.org/browse/FCREPO-3209
Ensures inventory state block contains all files for each version
1. Build and run migration-utils **without** this patch
- Observe that the `state` block for any version (except the first) only contains the files changed in that version
1. Build and run migration-utils **with** this patch
- Observe that the `state` block for any version (except the first) contains all files in that version
@fcrepo4/committers, @pwinckles

Ensure inventory state block contains all files for each version

---

src/main/java/org/fcrepo/migration/handlers/ocfl/ArchiveGroupHandler.java
src/main/java/org/fcrepo/migration/handlers/ocfl/PersistencePaths.java
src/main/java/org/fcrepo/migration/handlers/ocfl/ResourceHeaders.java
src/test/java/org/fcrepo/migration/handlers/ocfl/ArchiveGroupHandlerTest.java
src/test/java/org/fcrepo/migration/handlers/ocfl/PersistencePathsTest.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3376
Updates the migration utils to produce F6 objects using the new layout (https://wiki.lyrasis.org/display/FF/Design+-+Fedora+OCFL+Object+Structure)
F6 in main has not been updated yet to support this format, so this PR should not be merged until it has.
Run the migration utils and start F6 on the output.

update migration utils to produce F6 objects using the new layout

---

src/main/java/org/fcrepo/migration/PicocliMigrator.java
src/main/java/org/fcrepo/migration/handlers/ocfl/ArchiveGroupHandler.java

**JIRA Ticket**: none
Calvin is still having issues with running out of file descriptors. I cannot reproduce the issue locally, so this is another attempt at fixing the problem. I suspect that Tika maybe creating some additional resources that were not being closed. Tika is only used when a datastream's media type is not already known, which could be why I'm having trouble reproducing the problem with my datasets.

move tika stream into try-with

---

src/main/java/org/fcrepo/migration/FedoraObjectProcessor.java
src/main/java/org/fcrepo/migration/Migrator.java
src/main/java/org/fcrepo/migration/PicocliMigrator.java
src/main/java/org/fcrepo/migration/foxml/FoxmlInputStreamFedoraObjectProcessor.java

**JIRA Ticket**: none
If you're using the resume functionality or a pid list then some objects are skipped. Before this change, the skipped objects did not have their associated resources closed. This change closes those resources.
Run the tooling with a pid list that excludes a large number of objects and you should not run out of file descriptors.

close resources when they are skipped

---

README.md
src/main/java/org/fcrepo/migration/Migrator.java
src/main/java/org/fcrepo/migration/PicocliMigrator.java
src/main/java/org/fcrepo/migration/foxml/FoxmlInputStreamFedoraObjectProcessor.java
src/main/java/org/fcrepo/migration/handlers/ObjectAbstractionStreamingFedoraObjectHandler.java
src/test/java/org/fcrepo/migration/pidlist/UserProvidedPidListManagerIT.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3460
Resolve problems introduced into processing state when using the `--continue-on-error` flag to skip errors
Update README with current flags and their usage
Clean up resources after exceptions thrown while processing an object, in order to start with a clean state for processing the next object in the queue.
Documentation of `--continue-on-error` flag in README, other minor usage doc updates
I used a test set of 15 test objects to migrate, and deleted some datastreams from the F3 filesystem.
* First test: no continue-on-error, two datastreams deleted
Expected: migration halts after first missing datastream
Actual = Expected
* Second test: continue-on-error, datastreams in two consecutive objects deleted
Expected: migration skips …

Fcrepo 3460:  Improve processing with --continue-on-error

---

README.md
src/main/java/org/fcrepo/migration/PicocliMigrator.java
src/main/java/org/fcrepo/migration/handlers/ocfl/ArchiveGroupHandler.java
src/main/java/org/fcrepo/migration/handlers/ocfl/PlainOcflObjectSession.java
src/test/java/org/fcrepo/migration/handlers/ocfl/ArchiveGroupHandlerTest.java
src/test/resources/spring/ocfl-pid-it-setup.xml
src/test/resources/spring/ocfl-user-it-setup.xml

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3211
* Objects and datastreams that are in a Deleted state are migrated and then removed from the head version
* By default Inactive objects and datastreams are migrated the same as Active objects and datastreams
* A flag, `-I`, was added to migrate Inactive objects and datastreams the same as Deleted objects and datastreams
* If an object is in a Deleted state, then this state also applies to all of its datastreams
Migrate F3 content that contains Deleted or Inactive resources. See that they are not present in the head version, but are in earlier versions. Start F6 on the migrated content.

Fix Deleted and Inactive migration

---

src/test/java/org/fcrepo/migration/handlers/ocfl/ArchiveGroupHandlerTest.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3524
**This PR depends on https://github.com/fcrepo/fcrepo-storage-ocfl/pull/20**
Fixes a couple of tests that were expecting `contentSize` to be a `Long`.

fix tests after content size type change

---

src/main/java/org/fcrepo/migration/PicocliMigrator.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3556
Adds a `data` directory under the `--target` directory as Fedora 6 expects this by default. Also renames the `ocfl` directory to `ocfl-root`
Migrate some records, stand up F6 with `-Dfcrepo.home=<targetDir from migration>` and it should display the records with no additional steps.
Tag (@ mention) interested parties or, if unsure, @fcrepo-exts/committers

Add a new data directory

---

src/main/java/org/fcrepo/migration/OcflSessionFactoryFactoryBean.java
src/test/java/org/fcrepo/migration/handlers/ocfl/ArchiveGroupHandlerTest.java
src/test/java/org/fcrepo/migration/handlers/ocfl/PlainOcflObjectSessionFactoryTest.java
src/test/java/org/fcrepo/migration/handlers/ocfl/PlainOcflObjectSessionTest.java

**Jira:** https://jira.lyrasis.org/browse/FCREPO-3590
**This PR depends on https://github.com/fcrepo/fcrepo-storage-ocfl/pull/27**
Upgrades ocfl-java to the latest version.
A key difference in this version is that the storage layout extension definition is moved into the `extensions` directory. While the layout extension we're using has not been merged yet, it is unlikely that it'll need to be updated again.
This change does mean that the layout config in the storage root will no longer be read. Existing repositories with the storage layout in the old location are still usable, but `ocfl-java` will **not** write the storage layout to the new location for an existing repository. You either need to recreate the repository or write it manually.
To manually create it, write the following to …

upgraded to ocfl-java 0.2

---

src/test/java/org/fcrepo/migration/pidlist/ResumePidListManagerIT.java
src/test/java/org/fcrepo/migration/pidlist/UserProvidedPidListManagerIT.java

The ITests were broken after upgrading to ocfl-java 0.2 due to the addition of the `extensions` directory. Unclear why this wasn't caught before.

fixed the ITs

---

src/main/java/org/fcrepo/migration/PicocliMigrator.java
src/main/java/org/fcrepo/migration/foxml/DirectoryScanningIDResolver.java
src/main/java/org/fcrepo/migration/foxml/InternalIDResolver.java
src/test/java/org/fcrepo/migration/Example1TestSuite.java
src/test/java/org/fcrepo/migration/PicocliIT.java

**JIRA Ticket**: (https://jira.lyrasis.org/browse/FCREPO-3618)
* Other Relevant Links (Mailing list discussion, related pull requests, etc.)
Updates target-dir to be the storage root for PLAIN_OCFL (target-dir still contains data/ocfl-root for FEDORA_OCFL). Puts index dir and pid dir into a new working-dir.
The index-dir option is removed, and the working-dir option is added.
java -jar migration-utils-6.0.0-SNAPSHOT-driver.jar --source-type=legacy --datastreams-dir=<datastreams_dir> --objects-dir=<objects_dir> --target-dir=<target_dir> --migration-type=FEDORA_OCFL --working-dir=<working_dir> --limit=1
* <target_dir> should contain data/ocfl-root
* <working_dir> should contain index/ and pid/
java -jar migration-utils-6.0.0-SNAPSHOT-driver.jar --source-type=legacy …

FCREPO-3618 - update target-dir and working-dir

---

src/main/java/org/fcrepo/migration/OcflSessionFactoryFactoryBean.java
src/main/java/org/fcrepo/migration/PicocliMigrator.java
src/test/java/org/fcrepo/migration/PicocliIT.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3582
Adds a new `--algorithm` option to choose between sha256 or sha512 inventory manifests.
Migration some sample data, get inventory.json with sha512 digests. Then run the same command with `--algorithm sha256` and get sha256 digests.
Tag (@ mention) interested parties or, if unsure, @fcrepo-exts/committers

Make the digest algorithm configurable

---

src/main/java/org/fcrepo/migration/handlers/ocfl/ArchiveGroupHandler.java
src/test/java/org/fcrepo/migration/PicocliIT.java
src/test/java/org/fcrepo/migration/handlers/ocfl/ArchiveGroupHandlerTest.java

PLAIN_OCFL OCFL object IDs
* * *
**JIRA Ticket**: (https://jira.lyrasis.org/browse/FCREPO-3624)
This PR updates the PLAIN_OCFL handling to use the fedora 3 pid as the OCFL object ID, instead of info:fedora/<pid>.
There's an automated test for this, but to verify manually, run a PLAIN_OCFL migration and verify that the OCFL ID of the objects don't include the info:fedora/ prefix.

for PLAIN_OCFL migrations, use the fedora3 pid as the OCFL object id

---

src/main/java/org/fcrepo/migration/handlers/ocfl/ArchiveGroupHandler.java
src/test/java/org/fcrepo/migration/PicocliIT.java
src/test/java/org/fcrepo/migration/handlers/ocfl/ArchiveGroupHandlerTest.java

Reverts fcrepo-exts/migration-utils#148
Does not mesh with the prior commit.

Revert "for PLAIN_OCFL migrations, use the fedora3 pid as the OCFL object id"

---

.gitignore
src/main/java/org/fcrepo/migration/handlers/ocfl/ArchiveGroupHandler.java
src/test/java/org/fcrepo/migration/handlers/ocfl/ArchiveGroupHandlerTest.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3608 & https://jira.lyrasis.org/browse/FCREPO-3605
**This PR requires https://github.com/fcrepo/fcrepo-storage-ocfl/pull/31 to build**
* Adds the new `mementoCreatedDate` and `headersVersion` headers
Do a migration and you should see the headers in the output.

added new headers: headersVersion, mementoCreatedDate

---

src/main/java/org/fcrepo/migration/handlers/ocfl/ArchiveGroupHandler.java
src/main/java/org/fcrepo/migration/handlers/ocfl/PlainOcflObjectSession.java
src/test/java/org/fcrepo/migration/PicocliIT.java

Check for existing object before migrating
* * *
**JIRA Ticket**: (https://jira.lyrasis.org/browse/FCREPO-3643)
When migrating an object, if the object already exists in the OCFL repo, throw an exception instead of migrating content on top of what's already there.
There are a couple automated tests, but to test manually, run the migration over the same content twice - it should fail the second time because the first object was already migrated.
Documentation will need to be checked/updated.

Check for existing object before migrating

---

README.md
src/main/java/org/fcrepo/migration/PicocliMigrator.java
src/main/java/org/fcrepo/migration/handlers/ocfl/ArchiveGroupHandler.java
src/test/java/org/fcrepo/migration/PicocliIT.java

migrate FOXML file as deleted
* * *
**JIRA Ticket**: (https://jira.lyrasis.org/browse/FCREPO-3639)
For --foxml-file migrations - after migrating FOXML into the OCFL object, it deletes the FOXML so it's in the object history, but not a currently active file.
Has automated test, but to test manually: migrate an object with the --foxml-file option, and verify that the FOXML is not in the latest object version, but is in a previous version.

migrate FOXML file as deleted

---

pom.xml
src/main/java/org/fcrepo/migration/foxml/NamespacePrefixMapper.java
src/main/java/org/fcrepo/migration/handlers/ocfl/ArchiveGroupHandler.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3689
* Upgrades to the current version of Jena
* Explicitly closes Jena resources so they don't go to the finalizer to cleanup
Everything should work the same, except it should hopefully use less memory and not get bogged down.

upgrade jena version and cleanup resources

---

src/main/java/org/fcrepo/migration/handlers/ocfl/PlainOcflObjectSessionFactory.java

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3711
**This PR will not build until https://github.com/fcrepo/fcrepo-storage-ocfl/pull/38 is merged**
Adds a method stub for an interface method introduced in the latest version of `fcrepo-storage-ocfl`
Nothing should be different.

add new method stub to plain ocfl session

---

src/main/java/org/fcrepo/migration/handlers/ocfl/ArchiveGroupHandler.java

Use UTC time for deleted resources final commit
* * *
**JIRA Ticket**: (https://fedora-repository.atlassian.net/browse/FCREPO-3716)
This PR uses UTC time for the final commit that handles deleted resources in the migration.
Try migrating an object that has the final deleted resources commit, and see that it uses local timezone. Apply this change, and it should use UTC time for the final commit instead.

use UTC time for deleted resources final commit

---

src/main/java/org/fcrepo/migration/PicocliMigrator.java
src/main/java/org/fcrepo/migration/handlers/ocfl/ArchiveGroupHandler.java
src/test/java/org/fcrepo/migration/handlers/ocfl/ArchiveGroupHandlerTest.java
src/test/resources/inline-akubra/datastreams/dlmap/e/9e/b4/info%3Afedora%2F1711.dl%3AAccess-policy-open-access-UW-Madison-all%2FXACML%2FXACML.0
src/test/resources/inline-akubra/objects/dlmap/7/7e/6e/info%3Afedora%2F1711.dl%3AAccess-policy-open-access-UW-Madison-all

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3737
1. RELS-EXT triples are extracted and added to the resource container
2. RELS-INT triples are extracted and added to the binary description of the resource they apply to
3. If `RELS-INT` contains a `downloadFilename` triple, then the file name in the associated resource is updated
Migrate Fedora 3 content and examine the results to see that the RELS-* triples are now on the migrated RDF resources.
Note: The UW-Madison dataset is now no longer useful because there are some data problems with the RELS-* files and Jena will not parse them.

Add RELS-* triples to the appropriate RDF resource

---

pom.xml
src/main/java/org/fcrepo/migration/handlers/ocfl/ArchiveGroupHandler.java
src/test/java/org/fcrepo/migration/handlers/ocfl/ArchiveGroupHandlerTest.java

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3740
1. Resolves the filename of a binary by checking RELS-INT, the datastream label, and the datastream name, in that order. This more closely mimics [the behavior of Fedora 3](https://github.com/fcrepo3/fcrepo/blob/37df51b9b857fd12c6ab8269820d406c3c4ad774/fcrepo-server/src/main/java/org/fcrepo/server/rest/DatastreamFilenameHelper.java).
2. Fixes a bug where removing a RELS-INT download filename did not update the filename on the associated resource
3. Changes the behavior when `--extensions` is specified to **not** affect the binary resource's id, and only change its filename
Do a migration and see that label is now used to create the filename when there is not a RELS-INT relationship and a label exists. …

Use datastream label to construct filename

---

src/test/java/org/fcrepo/migration/PicocliIT.java

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3863
Tests in `PicocliIT` were matching against the namaste file `0=ocfl_1.0`. With fcrepo-storage-ocfl upgrading to ocfl-java 1.5.0 all newly migrated OCFL objects are version 1.1.
This modifies the test to instead grab the last part of the Path object (filename or directory), convert it to a String (otherwise it uses a Path match which is the whole filename) and match against `0=ocfl_1.`
Tests pass
Any additional information that you think would be helpful when reviewing this PR.
Example:
* Does this change require documentation to be updated? 
* Does this change add any new dependencies? 
* Does this change require any other modifications to be made to the repository (ie. Regeneration activity, etc.)? 
* Could this …

Alter test assertion to allow for ocfl 1.0 and 1.1

---

README.md
src/main/java/org/fcrepo/migration/PicocliMigrator.java
src/main/java/org/fcrepo/migration/handlers/ocfl/ArchiveGroupHandler.java
src/test/java/org/fcrepo/migration/InlineXmlIT.java
src/test/java/org/fcrepo/migration/handlers/ocfl/ArchiveGroupHandlerTest.java
src/test/java/org/fcrepo/migration/pidlist/HeadOnlyIT.java
src/test/resources/spring/inline-disabled-it-setup.xml
src/test/resources/spring/inline-invalid-it-setup.xml
src/test/resources/spring/inline-it-setup.xml
src/test/resources/spring/ocfl-pid-it-setup.xml
src/test/resources/spring/ocfl-user-it-setup.xml

**Migrate DC datastream as RDF properties**
* * *
**JIRA Ticket**: https://fedora-repository.atlassian.net/jira/software/c/projects/FCREPO/issues/FCREPO-3878
Adds the default feature of indexing DC datastreams into object properties where they exist. This feature can be turned off with a commandline argument ```--disable-dc``` 
Run a migration on fedora3 objects with and without DC datastreams and test for the existance of the properties in the resulting OCFL ntriples container files
Example:
* Does this change require documentation to be updated? 
* Does this change add any new dependencies? 
* Does this change require any other modifications to be made to the repository (ie. Regeneration activity, etc.)? 
* Could this change impact execution of existing code?

Fcrepo 3878 - Migrate DC datastream as RDF properties

---

src/main/resources/logback.xml

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-4005
Adds the full ISO-8601 date to log messages
Running a migration before this PR:
```
> java -jar target/migration-utils-6.6.0-SNAPSHOT-driver.jar -t akubra -d ../testing_helper/fedora_3_test/dsDir/ -o ../testing_helper/fedora_3_test/objectDir -a ../testing_helper/migration_output/output -i ../testing_helper/migration_output/working
INFO 11:13:51.062 (InternalIDResolver) Building an index of all the datastreams in "../testing_helper/fedora_3_test/dsDir"...
INFO 11:13:51.543 (Migrator) Processing "example:1"...
WARN 11:13:51.665 (ArchiveGroupHandler) info:fedora/example:1/RELS-EXT: missing/invalid digest. Writing resource & continuing.
```
Running a migration with this PR
```
> java -jar …
```

Add full date to log messages
