src/main/java/org/fcrepo/migration/DatastreamVersion.java, src/main/java/org/fcrepo/migration/foxml11/Foxml11InputStreamFedoraObjectProcessor.java, src/main/java/org/fcrepo/migration/foxml11/URLCachedContent.java, src/main/java/org/fcrepo/migration/handlers/BasicObjectVersionHandler.java, src/main/resources/spring/migration-bean.xml
Resolves https://jira.duraspace.org/browse/FCREPO-1412
=> Added migration support for R and X datastreams.

pom.xml, src/main/java/org/fcrepo/migration/MigrationIDMapper.java, src/main/java/org/fcrepo/migration/handlers/BasicObjectVersionHandler.java, src/main/java/org/fcrepo/migration/idmapers/SimpleIDMapper.java, src/test/java/org/fcrepo/migration/handlers/BasicObjectVersionHandlerIT.java, src/test/resources/exported/example2-foxml.xml, src/test/resources/spring/it-setup.xml
Resolves https://jira.duraspace.org/browse/FCREPO-1491
=> Add support for object-to-object linking in migrated resources.

src/main/java/org/fcrepo/migration/handlers/BasicObjectVersionHandler.java, src/test/java/org/fcrepo/migration/handlers/BasicObjectVersionHandlerIT.java, src/test/resources/exported/example3-foxml.xml
https://jira.duraspace.org/browse/FCREPO-1536
=> Ensured that for each version RELS-INT is migrated last.

src/main/java/org/fcrepo/migration/ContentDigest.java, src/main/java/org/fcrepo/migration/DatastreamInfo.java, src/main/java/org/fcrepo/migration/DatastreamVersion.java, src/main/java/org/fcrepo/migration/ExternalContentURLMapper.java, src/main/java/org/fcrepo/migration/MigrationIDMapper.java, src/main/java/org/fcrepo/migration/ObjectInfo.java, src/main/java/org/fcrepo/migration/ObjectProperties.java, src/main/java/org/fcrepo/migration/ObjectProperty.java, src/main/java/org/fcrepo/migration/ObjectReference.java, src/main/java/org/fcrepo/migration/ObjectVersionReference.java, src/main/java/org/fcrepo/migration/StreamingFedoraObjectHandler.java, src/main/java/org/fcrepo/migration/handlers/BasicObjectVersionHandler.java
Relates to: https://jira.duraspace.org/browse/FCREPO-1549
=> Minor, update javadocs

README.md
See: https://jira.duraspace.org/browse/FCREPO-1745
I am assuming @mikedurbin wants to be added to the maintainers section.
=> added maintainers section

pom.xml
See: https://jira.duraspace.org/browse/FCREPO-1728
=> decouple build-tools version from project.version

conf/fedora2-native.xml, conf/fedora3-akubra.xml, conf/fedora3-exported.xml, conf/fedora3-legacy.xml, src/main/resources/spring/migration-bean.xml
Related to: https://jira.duraspace.org/browse/FCREPO-1768
=> Enable option for migration utils to work against an auth-protected F4

README.md
See #45 
@bscoleman See: https://github.com/ruebot/migration-utils/tree/issue-45#how-to-use -- let me know if that updated section address your issue.
@ajs6f @mikedurbin let me know what y'all think too :smile:
=> Update README to clarify location of the jar file. Address #45.

README.md, pom.xml, src/main/java/org/fcrepo/migration/handlers/BasicObjectVersionHandler.java, src/test/java/org/fcrepo/migration/handlers/BasicObjectVersionHandlerIT.java
https://jira.duraspace.org/browse/FCREPO-2545
=> Updated mapping of created/lastModified metadata.

.travis.yml, src/main/java/org/fcrepo/migration/Migrator.java, src/main/java/org/fcrepo/migration/f4clients/OCFLFedora4Client.java, src/main/java/org/fcrepo/migration/foxml/DirectoryScanningIDResolver.java, src/main/java/org/fcrepo/migration/handlers/BasicObjectVersionHandler.java, src/test/java/org/fcrepo/migration/f4clients/OCFLFedora4ClientIT.java, src/test/resources/spring/ocfl-it-setup.xml
Resolves: https://jira.duraspace.org/browse/FCREPO-3024
=> Add initial OCFL implementation

src/main/java/org/fcrepo/migration/f4clients/OCFLGoLangFedora4Client.java, src/test/java/org/fcrepo/migration/f4clients/OCFLGoLangFedora4ClientIT.java, src/test/resources/spring/ocfl-it-setup.xml
**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-3042
Renamed org.fcrepo.migration.f4clients.OCFLFedora4Client.java
to OCFLGoLangFedora4Client.java
and org.fcrepo.migration.f4clients.OCFLFedora4ClientIT.java
to OCFLGoLangFedora4ClientIT.java
Build the project and run the existing tests(?)
=> Renamed OCFLFedora4Client and OCFLFedora4ClientIT

.travis.yml, README.md, pom.xml
Resolves: https://jira.duraspace.org/browse/FCREPO-3043
Enables build-compatibility with either Java 8 or 11.
* Build the project with Java 8
* Build the project with Java 11
@fcrepo4-exts/migration-utils-committers
=> Add compatibility for Java 11

pom.xml
Related to: https://jira.duraspace.org/browse/FCREPO-3045
=> Remove temporary Maven 'repository'

src/main/java/org/fcrepo/migration/f4clients/OCFLFedora4Client.java, src/test/java/org/fcrepo/migration/f4clients/OCFLFedora4ClientIT.java
**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-3084
Added the createOrUpdateNonRDFResource method in the OCFLFedora4Client
class (copied from OCFLGoLangFedora4Client) and a simple test.
Run the included test.
=> Added the createOrUpdateNonRDFResource method

pom.xml, src/main/java/org/fcrepo/migration/foxml/DirectoryScanningIDResolver.java, src/main/java/org/fcrepo/migration/idmappers/OpaqueIDMapper.java
Resolves: https://jira.duraspace.org/browse/FCREPO-3085
=> Update dependencies based on security vulnerabilities

src/test/java/org/fcrepo/migration/f4clients/OCFLFedora4ClientIT.java, src/test/java/org/fcrepo/migration/f4clients/OCFLFedora4ClientTest.java, src/test/resources/spring/ocfl-go-it-setup.xml, src/test/resources/spring/ocfl-it-setup.xml, src/test/resources/staging/.gitignore
Resolves: https://github.com/fcrepo4-exts/migration-utils/issues/71
=> Ensure that integration tests do not leave persisted test data

conf/fedora3.xml, src/main/java/org/fcrepo/migration/f4clients/OCFLFedora4Client.java
Resolves: https://github.com/fcrepo4-exts/migration-utils/issues/75
=> Fix example execution

conf/fedora3.xml, src/main/java/org/fcrepo/migration/Fedora4Client.java, src/main/java/org/fcrepo/migration/Migrator.java, src/main/java/org/fcrepo/migration/f4clients/OCFLFedora4Client.java, src/main/java/org/fcrepo/migration/f4clients/OCFLGoLangFedora4Client.java, src/main/java/org/fcrepo/migration/f4clients/StatelessFedora4Client.java
Resolves: https://github.com/fcrepo4-exts/migration-utils/issues/73
=> Cleanly shutdown after migrator has completed

.gitignore, conf/fedora3.xml, src/main/java/org/fcrepo/migration/Fedora4Client.java, src/main/java/org/fcrepo/migration/Migrator.java, src/main/java/org/fcrepo/migration/f4clients/OCFLFedora4Client.java, src/main/java/org/fcrepo/migration/f4clients/OCFLGoLangFedora4Client.java, src/main/java/org/fcrepo/migration/f4clients/StatelessFedora4Client.java
Uses Spring lifecycle hooks to close OCFL client.
=> change OCFLFedora4Client to be closed via Spring lifecycle

src/main/java/org/fcrepo/migration/f4clients/OCFLFedora4Client.java
I updated the ocfl-java API and changed `ObjectId` to `ObjectVersionId`.
=> update based on changes in ocfl-java api

src/main/java/org/fcrepo/migration/handlers/ocfl/ArchiveGroupHandler.java
Resolves: https://jira.duraspace.org/browse/FCREPO-3118
=> Change RDF serialization to n-triples

pom.xml
Treat the source and target as Java 11 as it is required to run anyways.
@fcrepo4-exts/committers
=> Do java 11 all the way

src/main/java/org/fcrepo/migration/handlers/ocfl/ArchiveGroupHandler.java
Resolves: https://jira.duraspace.org/browse/FCREPO-3125
=> Adds size and digest info to generated OCFL files

.travis.yml, README.md
Updates to point at the travis-ci.com testing framework. Also removes unnecessary `sudo: required`
@fcrepo4-exts/committers
=> Update for travis-ci.com

README.md, pom.xml, src/main/java/org/fcrepo/migration/PicocliMigrator.java
Resolves: https://jira.lyrasis.org/browse/FCREPO-3107
=> Picocli testing

README.md
Related to: https://jira.lyrasis.org/browse/FCREPO-3132
=> README updates related to "Address usability feedback"

README.md
**JIRA Ticket**:  https://jira.lyrasis.org/browse/FCREPO-3141
Update README to call out runtime dependency on Java 11, build dependency on Java 11 and Maven 3.1+.  Update project maintainer.
@awoods
=> Update Java, Maven dependency, maintainers

README.md, src/main/java/org/fcrepo/migration/PicocliMigrator.java
**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3143
* Make the layout parameter value case-insensitive (as the source-type parameter already is)
* Standardize parameter values to lowercase in help documentation, README
Run the migration utility with source-type, layout parameter values in either uppercase or lowercase.  Results should be the same, regardless of parameter value capitalization.
@awoods
=> Standardize parameter values

src/main/java/org/fcrepo/migration/f4clients/OCFLFedora4Client.java, src/test/java/org/fcrepo/migration/f4clients/OCFLFedora4ClientIT.java, src/test/resources/ocflStorage/ocfl_layout.json
Updates ocfl-client creation
* This should not be merged until I've released a new `ocfl-java` snapshot, which I will do next Monday (Dec 2).
* The layout is now highly customizable, and you should be able to make it do whatever you want. I just set it to some defaults.
* The layout config will change at least one more time after the spec is finalized and the layout extensions are defined.
@awoods
=> updated ocfl client creation to match ocfl-java changes

pom.xml, src/main/java/org/fcrepo/migration/f4clients/OCFLFedora4Client.java
Updates to the latest `ocfl-java` snapshot version.
@awoods
=> updated to the latest ocfl-java snapshot

src/main/java/org/fcrepo/migration/Migrator.java, src/main/java/org/fcrepo/migration/f4clients/OCFLFedora4Client.java, src/main/java/org/fcrepo/migration/foxml/DirectoryScanningIDResolver.java, src/main/java/org/fcrepo/migration/foxml/NamespacePrefixMapper.java, src/main/java/org/fcrepo/migration/idmappers/OpaqueIDMapper.java, src/main/java/org/fcrepo/migration/pidlist/ResumePidListManager.java, src/main/java/org/fcrepo/migration/pidlist/UserProvidedPidListManager.java, src/test/java/org/fcrepo/migration/Example1TestSuite.java
**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3191
Closes resources that were left open.
@awoods @birkland
=> Close open resources

README.md
- the --working-dir option in the README examples does not exist; it should be --target-dir.
=> Correct typo in README examples.

.github/PULL_REQUEST_TEMPLATE.md, README.md, pom.xml, src/main/java/org/fcrepo/migration/Migrator.java
No  functional  changes. 
Tag (@ mention) interested parties or, if unsure, @fcrepo/committers
=> Transfer repo to the 'fcrepo-exts' GitHub org

src/main/java/org/fcrepo/migration/foxml/FoxmlInputStreamFedoraObjectProcessor.java
**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3441
Closes open files in the F3 migration code
Run migration on a large number of files
=> don't leave files open

src/main/java/org/fcrepo/migration/handlers/ocfl/PlainOcflObjectSession.java, src/main/java/org/fcrepo/migration/handlers/ocfl/PlainOcflObjectSessionFactory.java, src/test/java/org/fcrepo/migration/handlers/ocfl/PlainOcflObjectSessionFactoryTest.java
Companion PR to https://github.com/fcrepo-exts/fcrepo-storage-ocfl/pull/13
=> remove session map from session factory

src/main/java/org/fcrepo/migration/handlers/ocfl/ArchiveGroupHandler.java, src/test/java/org/fcrepo/migration/handlers/ocfl/ArchiveGroupHandlerTest.java
**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3461
Creates a binary description for external resources when migrating from F3 to F6.
Migrate a F3 external resource to F6 and start F6 on the migrated content. The service should start without exception.
=> create binary description for external resources

src/main/java/org/fcrepo/migration/Migrator.java
**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3531
Exits after reaching the processing limit. Fixes #127 
Run the migration tool with a limit set and make sure it exists after processing the specified number of objects.
=> exit after reaching processing limit

src/main/java/org/fcrepo/migration/handlers/ocfl/PlainOcflObjectSession.java
Adds necessary method stub after https://github.com/fcrepo/fcrepo-storage-ocfl/pull/19
=> stubbed new storage-ocfl method

README.md, pom.xml
A couple of minor changes in preparation of the alpha release.
=> Readme and pom updates

pom.xml, src/main/java/org/fcrepo/migration/handlers/ocfl/PlainOcflObjectSession.java
**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3130
**This ticket depends on:** https://github.com/fcrepo/fcrepo-storage-ocfl/pull/24
Adds a method stub for the rollback method.
=> stub new ocfl storage method

src/main/java/org/fcrepo/migration/handlers/ocfl/ArchiveGroupHandler.java, src/test/java/org/fcrepo/migration/handlers/ocfl/ArchiveGroupHandlerTest.java
**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3123
Adds the new `archivalGroupId` field.
=> add support for archivalGroupId

pom.xml
Adds a maven profile for building without tests or other checks.
`mvn -Pfast-build clean install`
=> added profile for building artifact without tests or other checks

src/main/java/org/fcrepo/migration/PicocliMigrator.java, src/main/java/org/fcrepo/migration/handlers/ocfl/ArchiveGroupHandler.java, src/test/java/org/fcrepo/migration/PicocliIT.java, src/test/java/org/fcrepo/migration/handlers/ocfl/ArchiveGroupHandlerTest.java, src/test/resources/spring/inline-invalid-it-setup.xml, src/test/resources/spring/inline-it-setup.xml, src/test/resources/spring/ocfl-pid-it-setup.xml, src/test/resources/spring/ocfl-user-it-setup.xml
Add id-prefix param
* * *
**JIRA Ticket**: (https://jira.lyrasis.org/browse/FCREPO-3624)
Lets the user specify a different prefix to add to the fedora 3 pid for the ocfl object id.
Tests are included, but to test manually, run a migration with --id-prefix "" and verify that the ocfl object id doesn't include "info:fedora/".
=> Add id-prefix param

.github/workflows/build.yml
Resolves: https://jira.lyrasis.org/browse/FCREPO-3656
Tag (@ mention) interested parties or, if unsure, @fcrepo/committers
=> Adds deploy snapshot action to sonatype on merge into main.

src/main/java/org/fcrepo/migration/Migrator.java, src/main/java/org/fcrepo/migration/PicocliMigrator.java, src/main/java/org/fcrepo/migration/pidlist/UserProvidedPidListManager.java, src/test/java/org/fcrepo/migration/pidlist/ResumePidListManagerIT.java, src/test/java/org/fcrepo/migration/pidlist/UserProvidedPidListManagerIT.java
Check for pid list being fully processed
* * *
**JIRA Ticket**: (https://jira.lyrasis.org/browse/FCREPO-3680)
* Other Relevant Links (Mailing list discussion, related pull requests, etc.)
Stop iterating through the whole repository once a list of pids has been fully processed.
Run a migration batch with a small list of pids, and verify that the process exits after finishing the last pid, instead of continuing through the whole fedora repo.
=> check for a list of pids being fully processed and exit

pom.xml, src/main/java/org/fcrepo/migration/foxml/FileCachedContent.java, src/main/java/org/fcrepo/migration/foxml/FoxmlInputStreamFedoraObjectProcessor.java, src/main/java/org/fcrepo/migration/foxml/NamespacePrefixMapper.java, src/main/java/org/fcrepo/migration/handlers/ocfl/ArchiveGroupHandler.java
**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3758
Upgrades the storage-ocfl version and buffers a few input streams. This should improve performance.
No functional changes
=> added input stream buffers

pom.xml, src/main/java/org/fcrepo/migration/OcflSessionFactoryFactoryBean.java, src/test/java/org/fcrepo/migration/PicocliIT.java, src/test/java/org/fcrepo/migration/handlers/ocfl/ArchiveGroupHandlerTest.java, src/test/java/org/fcrepo/migration/handlers/ocfl/PlainOcflObjectSessionFactoryTest.java, src/test/java/org/fcrepo/migration/handlers/ocfl/PlainOcflObjectSessionTest.java
**Upgrades ocfl-java to 1.4.3**
* * *
**JIRA Ticket**:   https://fedora-repository.atlassian.net/browse/FCREPO-3793
* Other Relevant Links (Mailing list discussion, related pull requests, etc.)
No functional change.
A in-depth description of the changes made by this PR. Technical details and possible side effects.
Example:
* Changes x feature to such that y
* Added x
* Removed y
A description of what steps someone could take to:
* Reproduce the problem you are fixing (if applicable)
* Test that the Pull Request does what is intended.
* Please be as detailed as possible.
* Good testing instructions help get your PR completed faster.
Any additional information that you think would be helpful when reviewing this PR.
Example:
* Does this change require documentation to be updated? 
* Does …
=> Upgrades ocfl-java to 1.4.3

pom.xml
Adds the 6.2.0 release commits (though in the wrong location)
Tag (@ mention) interested parties or, if unsure, @fcrepo/committers
=> Add release commits

README.md
We did not have all the options documented here. Specifically the option to migrate as atomic resources.
Just documentation
Tag (@ mention) interested parties or, if unsure, @fcrepo-exts/committers
=> Update README with all options

pom.xml
This PR contains the work released in version 6.5.0. It should NOT be squash-merged.
=> Release 6.5.0

pom.xml, src/main/java/org/fcrepo/migration/OcflSessionFactoryFactoryBean.java, src/main/java/org/fcrepo/migration/handlers/ocfl/OcflObjectSessionWrapper.java, src/main/java/org/fcrepo/migration/handlers/ocfl/PlainOcflObjectSession.java, src/test/java/org/fcrepo/migration/pidlist/HeadOnlyIT.java
This PR contains the changes from release 6.5.1 -- it should be merged to main WITHOUT SQUASHING.
=> Release 6.5.1
